title: Muhammad Idris # your name (or website title) here
logo: "/images/rounded-frame.png" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  A Data Science bootcamp graduate trained in Analytics, Data & Database, Python, Statistics, Data Visualizations and Machine Learning. 
  <br><br>
  <a href="https://www.linkedin.com/in/muhammad-idris/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: G-XQDQZ7DL5E # your Google Analytics tracking ID here
